{% set data = load_setup_py_data(setup_file=RECIPE_DIR + "/../setup.py") %}

package:
  name: {{ data['name'] }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: |
    {{ PYTHON }} setup.py bdist_egg --exclude-source-files
    {{ PYTHON }} -m easy_install --no-deps dist/*.egg

requirements:
  host:
    - python
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

  run:
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  requires:
    - python

  source_files:
    - tests

  commands:
    - python tests/test_delta.py -v
    - python tests/test_opiterator.py -v
    - python tests/test_type.py -v

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
